import Menu from '@/components/layout/Menu'
import './globals.css'
import { Inter, Merriweather, Oswald } from 'next/font/google'
import { Suspense } from 'react'
import Cart from '@/components/Cart'
import { getMenu } from '@/lib/shopify/queries/menu'
const inter = Inter({ subsets: ['latin'] })

const merriweather = Merriweather({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

const oswald = Oswald({
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

async function getData(){
  return await getMenu("main-menu")

}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const menuData = await getData()
  console.log("menuData", menuData)
  return (
    <html lang="en">
      <body className={`${inter.className} ${merriweather.className} ${oswald.className}`}>
        <Suspense>
          <Menu menuData={menuData} />
              {children}
        </Suspense>
        <Cart />
      </body>
    </html>
  )
}
