import Menu from '@/components/layout/Menu'
import './globals.css'
import { Inter, Merriweather, Oswald } from 'next/font/google'
import { Suspense } from 'react'
import Cart from '@/components/Cart'

const inter = Inter({ subsets: ['latin'] })

const merriweather = Merriweather({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

const oswald = Oswald({
  weight: ['400', '500', '600', '700'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


// @ts-expect-error
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${merriweather.className} ${oswald.className}`}>
        <Suspense>
          <Menu />
              {children}
        </Suspense>
        <Cart />
      </body>
    </html>
  )
}
